### ISSUE TITLE
Incomplete .gitignore file

### ISSUE THREAD

**Issue by TanukiSharp** [kefniark/Kaaya#1]
Folder `.vscode` committed 😱

**Comment by kefniark** [comment]
yep did it on purpose for dev (I know, I'm lazy)
```
"editor.formatOnSave": true,
"editor.formatOnPaste": true,
```
I use that to enforce prettier execution on save for vscode, it's just faster that waiting to see the CI failing ^^

**Comment by TanukiSharp** [comment]
Agreed, I also like save-when-losing-focus to avoid embarrassing situations where you are sure your fix is correct and bang your head for not being fixed, when you realize you forgot to save ^^.
